version: "3.4"
services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $DB_USER -p $DB_PASS --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  api:
    build: .
    container_name: api
    restart: always
    env_file:
     - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"